name: CI

on:
  workflow_dispatch:

  push:
    paths-ignore:
      - 'README.md'

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: '-Dfile.encoding=utf-8 -Dorg.gradle.daemon=false'

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - uses: gradle/wrapper-validation-action@v1

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'

      - name: Test with Gradle
        run: ./gradlew clean check

      - name: Jacoco
        run: ./gradlew jacocoTestReport

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1